language: clojure
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.lein"
  - "$HOME/.m2"
before_script:
- phantomjs -v
script:
- lein cljfmt check
- lein do test, doo phantom test once
notifications:
  email: false
  slack:
    secure: cYo7mdNleQvaICXJ6e7AaPXgpG2zzY441x4+llKVXsnNwxZxqAsciMTB0921J8ZNfIfsg46G/msVO72uQLloBNVpqU3vAB5Z9EXECj6KVePu5zvieEW0TtWhqXDVs5+rGZ16ZdT5dnZKFvS9CHBy0Q+4lpDxXGmSWYG5WSJQjQzVUclaKxuuUGvyCUyJ8yZd858kUZ1bqetBmSfs3fZlYnoz3nNXpFHFikmNWeKylcUi7vieV2q1t6SOu5VkX57u0MDhKLvlpzmmehilAPAg4me71fBDs5ALnXEiUGnGFVCH8O11gS1jR+LzwJoT/ZvolYj1634KzwQtmlM0sK/2byabl6fmqi5+1lJ/loO8WZ6s/eIxcHGbvKTIxFqkDyzEltDlP6gAEQwgSloN3kSt5/kDYK9qmTwV6ueWYcU28kywCmgvz2XFxAF73VBHIVohklFJxonNgED+RjHQDI46/YGpfwm/+0e3ekFSEpD6YAvwgvu1+SvzoDV6qkXPc05gkh7MhvlNOGKJTDUux+/e8VBsqaZe0q4zHP9N9rg88UfLiCJomwihEIrIits56Z3OeM67sA4GicaZoa2MIdrqoIeD67jxxJ13z295F/8ZUkhLuD0vK7BkW3HxuvxTVijqdKpiTKh52dwQWNH6Z1eoCpqks1eBG9q/XPFLrc/8WmI=
